### ISSUE TITLE
Can't convert IVA file 

### ISSUE THREAD

**Issue by rgralnik** [Kagami/webm.js#10]
I am using Zeranoe's Windows build of ffmpeg to convert IVA files from a security camera so I can view them.  Here is the session I ran and the result - 

D:\Downloads\ffmpeg-20160913-c19da0c-win64-static\bin

> ffmpeg.exe -analyzeduration 1 -probesize 1000 -i "00-201304050008-0076.IVA" -c:v mpeg4  -map:v 0  "00-201304050008-0076.mp4"
> ffmpeg version N-81646-gc19da0c Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 5.4.0 (GCC)
>   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dx
> va2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-lib
> ebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --ena
> ble-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfree
> type --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enab
> le-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-lib
> openh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschr
> oedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheor
> a --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvo
> rbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --ena
> ble-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --e
> nable-decklink --enable-zlib
>   libavutil      55. 29.100 / 55. 29.100
>   libavcodec     57. 55.101 / 57. 55.101
>   libavformat    57. 48.103 / 57. 48.103
>   libavdevice    57.  0.102 / 57.  0.102
>   libavfilter     6. 62.100 /  6. 62.100
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  1.100 /  2.  1.100
>   libpostproc    54.  0.100 / 54.  0.100
> [avi @ 0000000000586fc0] Something went wrong during header parsing, I will igno
> re it and try to continue anyway.
> [avi @ 0000000000586fc0] Stream #0: not enough frames to estimate rate; consider
>  increasing probesize
> [avi @ 0000000000586fc0] Could not find codec parameters for stream 0 (Video: no
> ne (ITVD / 0x44565449), none, 320x240): unknown codec
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> Guessed Channel Layout for Input Stream #0.1 : stereo
> Input #0, avi, from 'U:\Case Files\Kamali_v_CalTrans\Evidence\00-201304050008-00
> 76.IVA':
>   Duration: 00:01:20.00, start: 0.000000, bitrate: 1677 kb/s
>     Stream #0:0: Video: none (ITVD / 0x44565449), none, 320x240, 30 fps, 30 tbr,
>  30 tbn, 30 tbc
>     Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels,
>  s16, 1411 kb/s
> File 'U:\Case Files\Kamali_v_CalTrans\Evidence\00-201304050008-0076.mp4' already
>  exists. Overwrite ? [y/N] y
> No decoder for stream #0:0, filtering impossible
> Error opening filters!

+++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++

Here is part of the actual .IVA file (NULLs and other non-printing  characters removed)

RIFF<!XAVI LISTŠithdivah~P00-201304050008-0076.IVA¼ýtÀ¹€|ÌvLM¥0°‘1Îð%ã·˜1Î@ðITVD++LISTŽhdrlavih85‚ð@ðLIST¤strlstrh8vidsITVDÿÿÿÿ@ðstrf((@ðITVDindx(00dcúISTŽstrlstrh8auds±@Õ5@Õ5strf(D¬±indx(01wbzD    LIST|strlstrh8cccsstrfindx(02ccšµLIST|strlstrh8wwmmstrfindx(03wmÂ¼JUNKêLIST@!Xmoviix00x=

+++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++

I have tried various versions of the command line from the simplest just giving the names of the input and output files to specifying codecs as well as settings for -analyzeduration and -probesize with no success.

Thanks for any help.
Richard

**Comment by Kagami** [comment]
This is the wrong repo for ffmpeg issues. You need to file it [here](https://trac.ffmpeg.org/).
